### ISSUE TITLE
Bitbucket clone location is different from VS & GitHub clone location

### ISSUE THREAD

**Issue by austindavenport** [MistyKuu/bitbucket-for-visual-studio#103]
The default cloning location for Visual Studio as a whole and GitHub is at `%userprofile%\source\repos\`. The Bitbucket VS extension's default cloning location is at `%userprofile%\Documents\source\repos\`.

Can this be changed to match Visual Studio's default cloning location? I don't want to have to change the cloning path each time I want to clone something from Bitbucket.

**Comment by MistyKuu** [comment]
It's read from registry. I suppose it's because it couldn't find the entry because you've never set it up. I'll change a fallback path, however you can configure it in Team Explorer - Settings - Global Settings

**Comment by MistyKuu** [comment]
Released in 1.41
