### ISSUE TITLE
Recently I cannot select my other teams in the plugin

### ISSUE THREAD

**Issue by faludigabor** [MistyKuu/bitbucket-for-visual-studio#117]
Cannot see other owned projects / teams . other than mine.

**Comment by nyoumans** [comment]
Same here - VS Pro 2017  -- 15.9.13+28307.718

**Comment by MistyKuu** [comment]
I'll check that out but it's related to the recent V1 to V2 migration. Probably there is some parameter which needs to be passed.

**Comment by MistyKuu** [comment]
Released in 1.41.1
