### ISSUE TITLE
FYI: Bitbucket Cloud account password removal may impact extension connection

### ISSUE THREAD

**Issue by codeaucafe** [MistyKuu/bitbucket-for-visual-studio#156]
Hello, I work on the the Bitbucket Cloud team. We have recently removed the ability to use Atlassian account passwords for Basic authentication with Git over HTTPS and the Bitbucket Cloud REST API; we now only support [app passwords](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/) for Basic auth instead. 

I have created this issue to warn users of the potential impact this change may cause them. Furthermore, it is likely that users may have issues getting connected/logging in to Bitbucket Cloud via this VS Studio extension. We have already seen one user bring this to our attention: (https://community.atlassian.com/t5/Bitbucket-discussions/Can-not-log-in-to-Bitbucket-in-Visual-Studio/td-p/1961323#U1962001).

You can find more details about this change in our community post:
https://community.atlassian.com/t5/Bitbucket-articles/Announcement-Bitbucket-Cloud-account-password-usage-for-Git-over/ba-p/1948231

**Comment by karter16** [comment]
Hi @DataDavD I just wanted to say thank you very much for taking the time to place this alert here.

I encountered this issue today, and was able to quickly find resolution thanks to you proactively raising this here.

Great customer service - very impressed!

Cheers,

Matt

**Comment by codeaucafe** [comment]
hey @karter16 no problem at all. I'm glad you got the issue resolved quickly using the provided links. 

Thank you very much for using Bitbucket!!!

Best,
David

**Comment by techjb** [comment]
@karter16 can you explain what did you do to sync visual studio to bitbucket? I tried app password, but it did not work.

**Comment by codeaucafe** [comment]
hey @techjb I updated your Atlassian community question. I believe the issue is that you need to use your Bitbucket Cloud username as your username instead of using your email as your username. App passwords do not support email as username.
