### ISSUE TITLE
An ability to work with PR comments directly from the plugin

### ISSUE THREAD

**Issue by DmytroLapshyn** [MistyKuu/bitbucket-for-visual-studio#17]
This one is rather a feature request. Currently one can view existing PR comments from the plugin, and it would be really nice to have an ability to add new ones directly from a diff view. For starters, I'd even think one can skip all the fancy formatting / previewing, and just provide a plain text editor where the reviewer can type markdown-formatted text. I'd also think a modal window would be enough to avoid all the hard work that would otherwise be needed to imitate the BitBucket's inline editor with VS text editor adornments which entail all sorts of fancy things related to the MEF cache. 

JFYI we had to add forced clean-up of the MEF cache in a plug-in installer for one of our customers because otherwise we couldn't guarantee stable work of our custom text taggers.

**Comment by MistyKuu** [comment]
This is one of the features which I've been planning to implement. To display inline diff view I use AvalonEdit control which is quite flexible and shouldn't be that hard to add this functionality. This has to be phased like you suggested, the first version will allow you to enter just plain text and later it can be extended. I'll play with it probably in the next week.

**Comment by MistyKuu** [comment]
Released in https://github.com/MistyKuu/bitbucket-for-visual-studio/milestone/1
