### ISSUE TITLE
Log in to local bitbucket gives an Error mapping types - missing http clone url

### ISSUE THREAD

**Issue by reeringh** [MistyKuu/bitbucket-for-visual-studio#19]
When I use the Extension on our local bitbucket system it gives me the following error on the login screen 

Unkown error. (Error mapping types.
Mapping types:
List'1 -> List'1

The log file is included.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1121754/logs.txt)

**Comment by MistyKuu** [comment]
At a first glance this is caused by line 25 here:

https://github.com/MistyKuu/bitbucket-for-visual-studio/blob/develop/Source/BitBucket.REST.API/Mappings/Converters/EnterpriseLinksTypeConverter.cs

When you login it tries to call endpoint get recent repositories to check the connection. It looks like one of your recent repositories doesn't have clone URL containing 'http' endpoint. Is it possible that bitbucket repository doesn't have it? This is definitely a bug anyway because in this particular case it shouldn't fail because connection is established. As for now you can cheat and login to your bitbucket web page and get rid of that repository from the list. It will have to be fixed in the incoming release.

**Comment by reeringh** [comment]
Deleted the complete repo in our bitbucket. 
Still getting this error. 
The Endpoint for the api also gives a 404..
Can I add this endpoint in a configuration.

**Comment by MistyKuu** [comment]
Sorry I don't understand. After removing all repositories now it gives 404?

**Comment by reeringh** [comment]
This are 2 separate things. 

1. When i try to connect to the rest api in my browser i get an 404,

2. I deleted the repo. then tried to login with the extension i got the same error.

**Comment by MistyKuu** [comment]
If you put this url in the browser and you get 404 then it means that your endpoint isn't valid.

**Comment by reeringh** [comment]
I know..

**Comment by MistyKuu** [comment]
If I remember correctly rest api url is configurable so you can check in bitbucket settings what the endpoint is if you have admin access

**Comment by reeringh** [comment]
I will try to get these admin rights so I can check these settings.

**Comment by reeringh** [comment]
I Checked the endpoint but there are multiple endpoints in bitbucket. 
What endpoint do you require and what is the purpose of this endpoint.

**Comment by MistyKuu** [comment]
Let me show you how it looks like on my side. My local bitbucket server url is http://localhost:7990
![image](https://user-images.githubusercontent.com/10333668/27873427-5ee3fb3e-61ac-11e7-97ab-30a5924da839.png)

When I put above url I get this:

![image](https://user-images.githubusercontent.com/10333668/27873407-4dbba29e-61ac-11e7-9b03-3e49e3c5e3a6.png)

**Comment by reeringh** [comment]
I get the exact same output. When I connect to out bitbucket installation.

Only different url of course

**Comment by MistyKuu** [comment]
ok cool, going back to original issue. Every repo contains this:
`{"clone":[{"href":"http://MistyK@localhost:7990/scm/tes/testrepo.git","name":"http"},{"href":"ssh://git@localhost:7999/tes/testrepo.git","name":"ssh"}]`

It looks like one of your repos don't have endpoint with name "http", could you tell me how is it possible and if you have any?

**Comment by reeringh** [comment]
All our connections are over ssh not over http. All the git connections are using ssh protocol

**Comment by reeringh** [comment]
i will try to let the admin turn this feature on. i wil get back to you.

**Comment by reeringh** [comment]
The Administrator has opened the connection over Http(s) And now your extension works. I Can log in and now I will test it further more. For now it looks great... Great Extension..

**Comment by MistyKuu** [comment]
Thanks, glad to hear!

**Comment by reeringh** [comment]
I will Close this bug. It all works perfect.....
