### ISSUE TITLE
Visual Studio 2017 slow performance

### ISSUE THREAD

**Issue by TheOnlyReality** [MistyKuu/bitbucket-for-visual-studio#21]
I am finding VS 2017 quite laggy since installing  and i am getting the attached message from VS 
![image](https://user-images.githubusercontent.com/30067135/28052609-563c270c-664f-11e7-91c1-098afd1a0048.png)

Environment Info Below

Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA342
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA342
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA342
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitClientVSPackage Extension   1.0
GitClientVSPackage Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2017.1.3    Build 108.0.20170613.154143
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Redgate SQL Search   2.3.10.1131
Search functionality for SQL Server databases, from within Visual Studio

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual Studio Tools for Unity   3.1.0.0
Visual Studio Tools for Unity

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by MistyKuu** [comment]
Hey,
I saw the message before for resharper and other extensions. Does this extension really impact the performance? When does it happen? At startup? Have you tried uninstalling it and comparing the performance?

**Comment by Iain-Stevenson** [comment]
I had this too. 16 seconds average delay in startup. 

Does it sign in immediately on VS startup, if so can that be deferred until its actually used?

The reason i ask is that my network can be variable  in its bandwidth and that may be a factor

**Comment by MistyKuu** [comment]
@Iain-Stevenson yes, and it must be a cause of the problem. I'll make this call async so it will just display loading bar instead.

**Comment by MistyKuu** [comment]
Released in https://github.com/MistyKuu/bitbucket-for-visual-studio/milestone/1. Please reopen the issue if issue still exists in 1.37 version.
