### ISSUE TITLE
Authenticate through SSO

### ISSUE THREAD

**Issue by Jacob-Daubendiek** [MistyKuu/bitbucket-for-visual-studio#22]
Im running an SSO plugin for bitbucket server and am having issues getting VS to authenticate. When we first setup the Bitbucket VS 2017 extension we provide the login information for bitbucket and connect. Once in we are able to see all the repos but when attempting to clone a non public repo we receive an error "failed to authenticate." 
Can this plugin pass the login information for cloning or is there a setting somewhere we need to change. We know it will clone when SSO is disabled on the server, but that is not an option.

**Comment by MistyKuu** [comment]
Hey, 
Could you give me more details? I don't understand why it wouldn't work.  Do you use the same credentials in Web browser which you use in the plug-in?

**Comment by Jacob-Daubendiek** [comment]
It started working the next day, but in general we were unable to access repos in our Bitbucket instance because Visual Studios would authenticate. After logging into the server via the plugin it needs to authenticate again to clone, it appears that the plugin was not passing the login information again. The next day we tried again and after logging in and attempting to clone, another box popped up requesting the login. not sure if it was a bug or if it was something else but i am working again. 
Thanks!

**Comment by MistyKuu** [comment]
It seems like you weren't authenticated in Git. I'm glad it's working,  closing.
