### ISSUE TITLE
Corporate BitBucket Server -- unable to get local issuer certificate

### ISSUE THREAD

**Issue by ramjet69** [MistyKuu/bitbucket-for-visual-studio#24]
Logging in to a corporate BitBucket server I am getting a certificate error. I have tried solutions from these two post 

https://developercommunity.visualstudio.com/content/problem/48517/visual-studio-2017-ssl-certificate-problem-unale-t.html

and

https://blogs.msdn.microsoft.com/tfssetup/2016/12/19/error-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

Either I am doing it wrong or they don't apply. The log is uploaded but it is pretty sparse.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1200726/logs.txt)

**Comment by MistyKuu** [comment]
Hey,
This is purely git CLI issue.  You can disable ssl however it is not recommended to do so.  There are many tutorials how to deal with ssl git certificates, I'm afraid I don't have enough expertise to help you with this
