### ISSUE TITLE
Not able to Push when using a proxy

### ISSUE THREAD

**Issue by Matti-Koopa** [MistyKuu/bitbucket-for-visual-studio#29]
I'm not able to complete a push request when I'm using a system proxy.

Visual Studio is configured to use the default proxy in devenv.exe.,config using:
```
    <system.net>
      <settings>
        <ipv6 enabled="true"/>
      </settings>
      <defaultProxy useDefaultCredentials="true" enabled="true">
        <proxy usesystemdefault="True" />
      </defaultProxy>
    </system.net>
```
This works and VS can access the internet (like in the "Extensions and Updates" window).

I tried Debugging using Fiddler.
When I'm doing a Push to Bitbucket, the only request that is send is

`GET https://api.bitbucket.org/2.0/teams?role=member&pagelen=50&page=1 HTTP/1.1` and it fails with code 502.
Previous requests to `GET https://bitbucket.org/api/v3/repos/myteam/myrepo HTTP/1.1` all fail with 404.

The Push fails after a few minutes with the following output in VS:
```
Error encountered while pushing to the remote repository: Git failed with a fatal error.
fatal: unable to access 'https://myname@bitbucket.org/myteam/myrepo.git/': Failed to connect to bitbucket.org port 443: Timed out
Pushing to https://myname@bitbucket.org/myteam/myrepo.git
```

**Comment by MistyKuu** [comment]
Could you please attach the log located here: %appdata%Roaming\GitClientVSExtension\Logs ?

**Comment by Matti-Koopa** [comment]
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1242532/logs.txt)

The last entry there seems to be about 6 minutes prior to the timeout error in VS though.

**Comment by MistyKuu** [comment]
If you put this `https://api.bitbucket.org/2.0/teams?role=member` in the browser do you get the response?

**Comment by Matti-Koopa** [comment]
My browser first asks my for credentials. When I enter my Atlassian account info, I get the following JSON:
`{"pagelen": 10, "values": [{"username": "ma14pace", "website": null, "display_name": "MA14 PACE", "uuid": "{46255de2-7876-43a0-9481-66ef1ad4b8f9}", "links": {"hooks": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace/hooks"}, "self": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace"}, "repositories": {"href": "https://api.bitbucket.org/2.0/repositories/ma14pace"}, "html": {"href": "https://bitbucket.org/ma14pace/"}, "followers": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace/followers"}, "avatar": {"href": "https://bitbucket.org/account/ma14pace/avatar/32/"}, "members": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace/members"}, "following": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace/following"}, "projects": {"href": "https://api.bitbucket.org/2.0/teams/ma14pace/projects/"}, "snippets": {"href": "https://api.bitbucket.org/2.0/snippets/ma14pace"}}, "created_on": "2017-08-16T07:30:14.579277+00:00", "location": null, "type": "team"}], "page": 1, "size": 1}`

**Comment by MistyKuu** [comment]
Interesting, I just read some articles and your settings should work.  Behind the scenes this extension uses `Restsharp` which uses `HttpWebRequest `class and it should pick up your config. I don't have an environment to reproduce this error, any chance that you download the source, build the project and run it locally? All you have to do is to clone it and F5 without additional configuration.

**Comment by Matti-Koopa** [comment]
So I uninstalled the extension, cloned this repo, installed the plugin development components für VS 2017 and pressed Run.
After it was finished building and loading, I logged in to the Atlassian cloud in the plugin again, added my local repos back and pushed the pending "Outgoing Commits".

There was no breakpoint / unhandled exception hit during this whole debugging session and the timeout was hiot without interruptions.
I enabled all "Common Language Runtime Exceptions" for "break when thrown" and tried again. The following exception was hit after a few minutes:
```
Microsoft.TeamFoundation.Git.Api.Cli.GitFatalException occurred
  HResult=0x80131500
  Message=Git failed with a fatal error.
fatal: unable to access 'https://MatthiasPorges@bitbucket.org/ma14pace/pace_botframework.git/': Failed to connect to bitbucket.org port 443: Timed out
Pushing to https://MatthiasPorges@bitbucket.org/ma14pace/pace_botframework.git
  Source=Microsoft.TeamFoundation.Git
  StackTrace:
   at Microsoft.TeamFoundation.Git.Internal.Operation.Start(IProcess process)
```
This was hit on unmanaged code.
![image](https://user-images.githubusercontent.com/10476794/29577816-2326d10c-876d-11e7-96c0-6a1f6da9b03f.png)

What additional debugging may I perform with this?

**Comment by MistyKuu** [comment]
Ok it's something different than I thought. If you are able to login it means that you do have access to API so proxy works. Pushing repo doesn't work which is a git command. Have you tried to push repository from your command line? I suppose you have to configure git to work with proxy.

**Comment by Matti-Koopa** [comment]
Oh wow - yeah apparently that was it. I followed this answer here: https://stackoverflow.com/questions/41038067/how-to-configure-npm-git-and-bower-for-visual-studio-behind-a-proxy

It works now. Weird that those commands don't follow the same proxy settings while being in the same VS tool windows (Team Explorer).
So it's not the addons fault. Really confused me, since all other actions were working.

Thank you for your support!
