### ISSUE TITLE
Ambiguous Error Message (Directory already exists)

### ISSUE THREAD

**Issue by bluedog13** [MistyKuu/bitbucket-for-visual-studio#34]
For some reason, when I am not able to find the project via Key during cloning, I see the error message "Directory already exists".  The directory does not exist at all 

<img width="261" alt="vs_bitbucket_error" src="https://user-images.githubusercontent.com/11997472/31300481-8d0df608-aab9-11e7-81a1-a012e7e8c621.PNG">

**Comment by MistyKuu** [comment]
It's because it combines directory with repo name. In this case repo name is empty so it checks if directory exists and it obviously exists. It's a bug.

**Comment by MistyKuu** [comment]
Released in 1.37.2
