### ISSUE TITLE
Unknown error on login in to BitBucket

### ISSUE THREAD

**Issue by joeldejong** [MistyKuu/bitbucket-for-visual-studio#35]
When I try to login I get this error:

![bitbucketloginerr](https://user-images.githubusercontent.com/15346253/31483871-6f073b00-af2e-11e7-8c5a-a41738fdde94.jpg)

**Comment by MistyKuu** [comment]
Please look at this. 
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/31
Also you can check logs for more info located here: %appdata%/gitclientvsextension/logs

**Comment by joeldejong** [comment]
That was it. Thanks!
