### ISSUE TITLE
Error on login (probably two factor auth)

### ISSUE THREAD

**Issue by totkeks** [MistyKuu/bitbucket-for-visual-studio#36]
When I login in Visual Studio 2017 I get the following error:

> Unknown error. (Data at the root level is invalid. Line 1, position 1.). Check Logs for more info.

Where can I find those logs?
I assume this has something to do with two factor auth and the login window/client not redirecting me to enter the tfa credentials.

**Comment by MistyKuu** [comment]
Please check this:
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/35

However if you say that you have 2FA enabled then you should read about App Passwords.
https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/
