### ISSUE TITLE
Problem during compilation

### ISSUE THREAD

**Issue by kpiekara** [MistyKuu/bitbucket-for-visual-studio#39]
I have a problem with building yours plugin. Maybe you already forced with that problem or maybe I'm missing some needed to be installed technology.

I able to build simple project VSIX (File/New/Project/Visual C#/Extensibility/VSIX Project),
I able to build my own plugins, 
		
Reproduce problem:
1. Clean repo
2. Open GitClientVS.sln
3. To be sure that all packages are installed ` nuget restore .\GitClientVS.sln`
```
NuGet Config files used:
    C:\REPO\NuGet.Config
    C:\Users\USER\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\USER\.nuget\packages\
    https://api.nuget.org/v3/index.json

Installed:
    50 package(s) to packages.config projects
```
4. Build solution

```
========== Build: 12 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "FindInstalledExtension" task failed unexpectedly.
System.Runtime.InteropServices.COMException (0x800700B7): ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath, String rootSuffix)
   at Microsoft.VsSDK.Build.Tasks.ExtensionManagerUtilities.GetSettingsManagerForDevenv(String rootSuffix)
   at Microsoft.VsSDK.Build.Tasks.FindInstalledExtension.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	GitClientVS.VisualStudio.UI			
```

About Microsoft Visual Studio:
Microsoft Visual Studio Professional 2017 
Version 15.4.4
VisualStudio.15.Release/15.4.4+27004.2009
Microsoft .NET Framework
Version 4.7.02053

Installed: Visual Studio extensions development: all stuff + all optional stuff

Unmarking `GitClientVS.VisualStudio.UI/Properties/VSIX/Deploy VSIX content to experimental istance for debbuging`, makes that compilation success, but it makes hard to debug extension.

**Comment by kpiekara** [comment]
Removing line (to times, it is duplicated):
```<Import Project="..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\build\Microsoft.VSSDK.BuildTools.props" Condition="Exists('..\..\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\build\Microsoft.VSSDK.BuildTools.props')" />```
in `GitClientVS.VisualStudio.UI.csproj` allowed me to build plugin and run experimental instance with that plugin.

Is this line needed in csproj?

**Comment by MistyKuu** [comment]
It adds below lines to msbuild configuration. I think it may break vsix creation.
```
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="VSSDK_NuGet_Configuration">
    <ThisPackageDirectory>$(MSBuildThisFileDirectory)..\</ThisPackageDirectory>
    <VSToolsPath>$(ThisPackageDirectory)\tools</VSToolsPath>
    <VsSDKInstall>$(VSToolsPath)\VSSDK</VsSDKInstall>
    <VsSDKIncludes>$(VsSDKInstall)\inc</VsSDKIncludes>
    <VsSDKToolsPath>$(VsSDKInstall)\bin</VsSDKToolsPath>
    <VsixSchemaPath>$(VsSDKInstall)\schemas\VSIXManifestSchema.xsd</VsixSchemaPath>
  </PropertyGroup>
</Project>
```

**Comment by kpiekara** [comment]
Does the project have any requirements beyond VS2017? Do I have to have specific things installed?

**Comment by MistyKuu** [comment]
No, I've been developing on Windows 10 with VS2017.

**Comment by MistyKuu** [comment]
Any update on that?

**Comment by kpiekara** [comment]
Nope, I left it. Unfortunately detecting project properties is not my area of interest, so I can not help.
