### ISSUE TITLE
Unable to find a remote matching: [object Set]

### ISSUE THREAD

**Issue by LeBlaaanc** [MistyKuu/bitbucket-for-visual-studio#40]
Hi, I'm trying to use a self hosted Bitbucket server and am getting one of the following errors:

When configured with the scheme as such:
`"codebucket.bitbucketHosts": ["https://my.com.company.tld"]`

`Unable to find a remote matching: [object Set]`

When configured without the scheme as such:
`"codebucket.bitbucketHosts": ["my.com.company.tld"]`

`Could not parse host name: my.com.company.tld`

Any idea what I am doing wrong?

**Comment by MistyKuu** [comment]
Where do you input this url? I don't get what this is: `"codebucket.bitbucketHosts": ["https://my.com.company.tld"]`
When you login to this extension just put `https://my.com.company.tld` and everything should work.

**Comment by LeBlaaanc** [comment]
Ah sorry wrong project I think, I meant to post this in the VS Code extension :X
