### ISSUE TITLE
Successful login to my company's Bitbucket, but no repo is shown?

### ISSUE THREAD

**Issue by FaridAhamat** [MistyKuu/bitbucket-for-visual-studio#41]
Something is wrong:

1. The login is too fast, it's instantaneous. I don't think any authentication even took place...
2. No repo is shown when I login?
3. Tried with wrong name/password, I still can login.

I think I'm using your product wrong, or your product is seriously wrong...

**Comment by MistyKuu** [comment]
Hey,
could you please attach log file located under %appdata%/gitclientvsextension/logs?

**Comment by FaridAhamat** [comment]
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1505223/logs.txt)

**Comment by MistyKuu** [comment]
From the logs point of view all looks fine. Could you please open https://bitbucket.lsretail.com/rest/api/1.0/profile/recent/repos and tell me what you see in the browser?

**Comment by FaridAhamat** [comment]
json array containing lists of all the repo that I have access to. I'm not sure what is the correct output here, but posting the full raw data doesn't sound like a good idea neither (I don't know if it's good or bad).

Tell me how the output should look like?

**Comment by MistyKuu** [comment]
It looks good. Do you have any proxy configured?

**Comment by MistyKuu** [comment]
Any update on that?
