### ISSUE TITLE
2017 v 15.5.2

### ISSUE THREAD

**Issue by ericbyrd** [MistyKuu/bitbucket-for-visual-studio#43]
Currently non-functional in VS 2017 15.5.2. The node in Team Explorer does not appear. Confirmed installed and enabled. Any plans on supporting this version of 2017?

**Comment by ericbyrd** [comment]
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1569725/logs.txt)

**Comment by IainStevenson** [comment]
I upgraded to VS 15.5.2 yesterday and installed this extension just now and it works . Cloned a repo from my cloud account to local.

**Comment by charithsoori** [comment]
Working nicely with 15.5.2

**Comment by MistyKuu** [comment]
I can't reproduce it. I'll reopen it when I know how to reproduce this issue.
