### ISSUE TITLE
Failed with fatal error, Repo not recognized, unable to connect from Visual Studio 2017 if other repos exist

### ISSUE THREAD

**Issue by papyr** [MistyKuu/bitbucket-for-visual-studio#44]
using the your extension from 1/19, both fail 1) a default _new_ install & if there were _previous_ repos where VS connected to TFS online or other places, **it wont connect and recognize the bitbucket.**

![image](https://user-images.githubusercontent.com/12733414/35137700-cf163eec-fcb8-11e7-97e4-48b4d75f9baa.png)

**How do you pull from existing Bitbucket GIT repo using Visual Studio 17?**

> Error "***_git failed with a fatal error. 'xyz' repository not found_*** "

 1. First, I added  BitBucket *Extension* from the marketplace
 2. Second, I tried to add the `Git remote string` as below with three types of options 
_____________
First I tried this string -> `https://<some_repo_owner>@bitbucket.org/<someaccountname>/<somereponame>.git` & `https://<somerepo_owner>@bitbucket.org/<someaccountname>/<reponame>`	then I tried the URL path based on youtube videos & the over settings page `https://bitbucket.org/myrepo/reponame/src`
______________
 3. I get errors that the **repo does not exist.**

**Comment by MistyKuu** [comment]
Local Git Repositories section is not a part of this extension. To clone remote repository from bitbucket just click here: 
![image](https://user-images.githubusercontent.com/10333668/36806387-26f65382-1cc0-11e8-96c5-fef8ef1e77f7.png)
