### ISSUE TITLE
VS 2017 15.4.5 : no repo found (BitBucket cloud - Mercurial repos)

### ISSUE THREAD

**Issue by metoule** [MistyKuu/bitbucket-for-visual-studio#46]
The plugin successfully managed to log in (as it properly retrieved my username), but the list of repos is empty.

When going to https://api.bitbucket.org/1.0/user/repositories in a browser, I see the proper list of repos (of course, I had to manually log in): 

![image](https://user-images.githubusercontent.com/24547430/35212004-030ec8a2-ff59-11e7-85a6-13193411e54f.png)

I also attach the extension logs.

[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1651253/logs.txt)

Note that all my repositories are using Mercurial, not Git.

**Comment by MistyKuu** [comment]
Sorry, this plugin is only for git repositories.

**Comment by metoule** [comment]
I apologize, I should have read the documentation more carefully.
That's a shame though, it seems like a nice extension.
