### ISSUE TITLE
login window in vs 2017 with update 15.5.6

### ISSUE THREAD

**Issue by devesh-bansal** [MistyKuu/bitbucket-for-visual-studio#47]
Hi,

Does not popup out login windows in VS 2017 (with 15.5.6 updates) , it gives error in log as
ERROR GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Unhandled Dispatcher GitClientVsExtensions Error

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitClientVS.UI.Views.LoginDialogView". ---> System.Windows.Markup.XamlParseException: Initialization of 'GitClientVS.UI.Styles.SharedResourceDictionary' threw an exception. ---> System.InvalidOperationException: 'MetroWindow' TargetType does not match type of element 'LoginDialogView'

**Comment by MistyKuu** [comment]
Are there repro steps?

**Comment by MistyKuu** [comment]
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/53
