### ISSUE TITLE
Login to self-hosted Bitbucket fails due to incorrectly formed API URL

### ISSUE THREAD

**Issue by msedmak** [MistyKuu/bitbucket-for-visual-studio#48]
Environment:

- Visual Studio Communitiy 2015 v 14.0.25431.01 Update 3 (confirmed on Visual Studio 2017 also)

- Bitbucket for VS plugin latest version

When logging into a self-hosted Bitbucket server, the login fails with an error visible in the attached image. 

![capture-vs-bitbucket](https://user-images.githubusercontent.com/6481187/36020287-76155028-0d82-11e8-9e16-cfeb6a27d47b.PNG)

The Bitbucket server is behind an nginx server. When I check the nginx log, I see the following error, telling me that the API url is not relative to the server URL entered in the LOGIN window:

![capture-vs-bitbucket-log](https://user-images.githubusercontent.com/6481187/36020364-b4b03212-0d82-11e8-871f-d10e143a021e.PNG)

Could you please check how the API url is constructed?

**Comment by MistyKuu** [comment]
Hey,
please attach the logs which are under %appdata%/gitclienvsextension/logs

**Comment by msedmak** [comment]
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1737091/logs.txt)
Sorry for the long wait - here they are!

**Comment by MistyKuu** [comment]
The project is opensource so you can check the code yourself. In logs you can find this address:
` https://<host>/rest/api/1.0/profile/recent/repos
`
Can you put it in the browser and tell me what you get?
I found exactly the same error here:
https://github.com/plivo/plivo-dotnet/issues/24
It seems that the real message is "400 Bad Request - request header or cookie too large".
I will have a look at `AddHandlers `method in the code to see if we don't increase header size infinitely.

**Comment by MistyKuu** [comment]
https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/48
