### ISSUE TITLE
Login error on Bitbucket Extension for Visual Studio 2015 & 2017

### ISSUE THREAD

**Issue by cainellinFTC** [MistyKuu/bitbucket-for-visual-studio#52]
I just installed Bitbucket extension in Visual Studio 2015 & 2017 but in both when I click login an error message appears.  

![image](https://user-images.githubusercontent.com/37626977/37717444-dc8afcc8-2d20-11e8-8319-e500dd6ad1d2.png)

This is the log:
2018-03-21 15:19:25,292 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2018-03-21 15:20:09,000 [1] INFO  BitBucket.REST.API.BitbucketClientFactory [(null)] - Calling CreateStandardBitBucketClient.
2018-03-21 15:20:09,011 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: user
2018-03-21 15:20:09,144 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - System.Xml.XmlException: Il tag di inizio 'BR' sulla riga 6, posizione 30 non corrisponde al tag di fine di 'FONT'. Riga 7, posizione 3.
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__5`1.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BitBucket.REST.API.Clients.Standard.UserClient.<GetUser>d__1.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BitBucket.REST.API.BitbucketClientFactory.<CreateStandardBitBucketClient>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Services.BitbucketService.<CreateBitbucketClient>d__14.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Services.BitbucketService.<LoginAsync>d__13.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Infrastructure.ViewModels.LoginDialogViewModel.<Connect>d__35.MoveNext()

**Comment by MistyKuu** [comment]
I tries to "GET"  https://api.bitbucket.org/2.0/user. Are you behind a proxy?

**Comment by MistyKuu** [comment]
Please upgrade to 1.37.3, reproduce this error and attach logs again. I've added more verbose logs in this update.

**Comment by cainellinFTC** [comment]
Upgraded to 1.37.3 ,
the proxy needs a user and password, but no prompt to insert them appears, I tried to put it in the config

  proxy bypassonlocal = "true" proxyaddress = "http: // user: password @ prox: port"

but it does not work,  this is the log:

2018-03-23 11:11:12,114 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2018-03-23 11:11:27,543 [1] INFO  BitBucket.REST.API.BitbucketClientFactory [(null)] - Calling CreateStandardBitBucketClient.
2018-03-23 11:11:27,555 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: user
2018-03-23 11:11:27,651 [27] ERROR BitBucket.REST.API.Serializers.NewtonsoftJsonSerializer [(null)] - Couldn't deserialize json: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
<BR>
<BR>
IP client: 10.120.160.128
<BR>
url: tcp://api.bitbucket.org:443/
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
Per assistenza contattare il supporto di rete Phoenix copiando il contenuto di questa pagina di errore nella Richiesta di Assistenza.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
. Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   in Newtonsoft.Json.JsonTextReader.ParseValue()
   in Newtonsoft.Json.JsonTextReader.Read()
   in Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   in Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   in Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   in BitBucket.REST.API.Serializers.NewtonsoftJsonSerializer.Deserialize[T](String json)
2018-03-23 11:11:27,664 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__5`1.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BitBucket.REST.API.Clients.Standard.UserClient.<GetUser>d__1.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BitBucket.REST.API.BitbucketClientFactory.<CreateStandardBitBucketClient>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Services.BitbucketService.<CreateBitbucketClient>d__14.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Services.BitbucketService.<LoginAsync>d__13.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in GitClientVS.Infrastructure.ViewModels.LoginDialogViewModel.<Connect>d__35.MoveNext()
2018-03-23 11:11:27,667 [1] ERROR GitClientVS.Infrastructure.Utils.ExceptionMapper [(null)] - Unknown error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.CheckResponseStatusCode(IRestResponse response)
   in BitBucket.REST.API.Wrappers.BitbucketRestClientBase.<ExecuteTaskAsync>d__5`1.MoveNext()
.......

**Comment by MistyKuu** [comment]
It's purely related to .NET applications. We use RestSharp which uses WebRequest class behind the scenes. Btw don't you have to configure proxy for https? Have you tried this?
`  proxy bypassonlocal = "true" proxyaddress = "http**s**: // user: password @ prox: port"`

**Comment by cainellinFTC** [comment]
I tried with https, but the result is:
  "ServicePointManager not support proxy with https"


2018-03-26 09:53:50,308 [1] INFO  GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Initialized GitClientVsPackage Extension
2018-03-26 09:54:05,141 [1] INFO  BitBucket.REST.API.BitbucketClientFactory [(null)] - Calling CreateStandardBitBucketClient.
2018-03-26 09:54:05,153 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://api.bitbucket.org/2.0/ Resource: user
2018-03-26 09:54:05,176 [1] ERROR GitClientVS.Infrastructure.Extensions.ViewModelsExtensions [(null)] - System.NotSupportedException: ServicePointManager non supporta proxy con schema https.

**Comment by MistyKuu** [comment]
I would really like to help you here but I don't know how to bypass this login page. It's internal authorization mechanism which requires you to login through this login page. The only way I can think of is to disable this login page. I will about something else in the meantime.

**Comment by cainellinFTC** [comment]
And how can disable the login page ?

**Comment by MistyKuu** [comment]
Isn't it your internal company login page?

**Comment by cainellinFTC** [comment]
I can't disable the proxy, and without proxy I can't access to the internet

**Comment by MistyKuu** [comment]
You shouldn't disable the proxy, you should use it. Tell me one thing - if you open the browser and put this in url:
 https://api.bitbucket.org/2.0/user

What happens? Were you asked about credentials at any point? I don't mean bitbucket credentials but your internal company credentials?

**Comment by cainellinFTC** [comment]
If I open the url with browser , the browser ask me proxy autentication, after login with internal company credentials, the browser ask me the bitbucket login and with my credential the result is this:

{"username": "cainellinFTC", "website": null, "display_name": "Nicola Cainelli", "account_id": "5ab0f5a03ce81c2a7cd31409", "links": {"hooks": {"href": "https://api.bitbucket.org/2.0/users/cainellinFTC/hooks"}, "self": {"href": "https://api.bitbucket.org/2.0/users/cainellinFTC"}, "repositories": {"href": "https://api.bitbucket.org/2.0/repositories/cainellinFTC"}, "html": {"href": "https://bitbucket.org/cainellinFTC/"}, "followers": {"href": "https://api.bitbucket.org/2.0/users/cainellinFTC/followers"}, "avatar": {"href": "https://bitbucket.org/account/cainellinFTC/avatar/32/"}, "following": {"href": "https://api.bitbucket.org/2.0/users/cainellinFTC/following"}, "snippets": {"href": "https://api.bitbucket.org/2.0/snippets/cainellinFTC"}}, "created_on": "2018-03-20T12:11:33.857946+00:00", "is_staff": false, "location": null, "type": "user", "uuid": "{7563db36-acbb-467d-80f2-ac86b8a450eb}"}

**Comment by MistyKuu** [comment]
**If I open the url with browser , the browser ask me proxy autentication**

You sure it's proxy settings? I don't think that the browser should ask for proxy credentials. It should have been configured upfront. I think it's SSO login page and that's the problem. I don't know how this extension can bypass this login page.

**Comment by cainellinFTC** [comment]
Yes I'm sure. In my company the internet navigation is blocked by proxy and every time that I try to navigate an url, I must to login with credentials. 
But the same happen if in visual studio I try to open nuget manager, visual studio ask me the proxy credentials and then works fine, I don't know why the bitbucket extension don't work

**Comment by MistyKuu** [comment]
Could you make a screenshot of this proxy dialog in nuget manager?

**Comment by cainellinFTC** [comment]
![image](https://user-images.githubusercontent.com/37626977/37902675-75da0d92-30f5-11e8-8b64-df76b813a56c.png)

**Comment by MistyKuu** [comment]
I suspect that the version of RestSharp which we use (105.2.3) doesn't use current proxy configured. I'll update it to the latest and we can retest.

**Comment by cainellinFTC** [comment]
Thank you very much , I'll wait the update

**Comment by MistyKuu** [comment]
Ok go ahead and try 1.37.4

**Comment by MistyKuu** [comment]
What proxy did you put?

**Comment by cainellinFTC** [comment]
I tried with address and credential

<defaultProxy useDefaultCredentials="false" enabled="true">
<proxy bypassonlocal="true" proxyaddress="http://username:password@myproxy:8080"/>
</defaultProxy>

with address only 

<defaultProxy useDefaultCredentials="false" enabled="true">
<proxy bypassonlocal="true" proxyaddress="http://myproxy:8080"/>
</defaultProxy>

and with system default

<defaultProxy useDefaultCredentials="true" enabled="true">
<proxy bypassonlocal="true" usesystemdefault="true" />
</defaultProxy>

**Comment by MistyKuu** [comment]
I'll implement dialog window where you'll be able to enter credentials and they will be stored in Credentials Manager in Windows. In the meantime you should configure your proxy to save credentials so it doesn't ask for them every time.

**Comment by MistyKuu** [comment]
Resolved in 1.37.5. Please reopen the issue if the problem persists.

**Comment by cainellinFTC** [comment]
Thanks a lot, it works perfectly !
