### ISSUE TITLE
The file remains in the "Changes" list.

### ISSUE THREAD

**Issue by superlapp** [MistyKuu/bitbucket-for-visual-studio#55]
Sometimes the file remains in the list of changes after the "Undo Changes" action.
The rollback operation in the file is successful.
The problem at the moment can be solved through the action "Discard" in SourceTree.

**Comment by MistyKuu** [comment]
Could I get a screenshot? Are you sure it's bitbucket extension not Visual Studio Git extension?

**Comment by superlapp** [comment]
Hello.
At the moment, I can not provide a screenshot, I was working on a remote desktop, I had to quickly solve the problem. Once the problem is repeated, I'll send a screenshot.
Hmm. How do I find out which provider performs the "Undo Changes" action?
![2](https://user-images.githubusercontent.com/21578151/38026907-9aa9cffc-3296-11e8-9def-3671949febca.PNG)
![1](https://user-images.githubusercontent.com/21578151/38026916-9f50119c-3296-11e8-9cc4-a6740b8886e5.PNG)

**Comment by MistyKuu** [comment]
Undo changes is not this extension, it's git extension built in Visual Studio. Some functionalities from bitbucket extension are synchronized with visual studio e.g current repository but the button Undo Changes is just a built in functionality from VS.
