### ISSUE TITLE
Ability to recursively clone git submodules of a repository

### ISSUE THREAD

**Issue by BooherB** [MistyKuu/bitbucket-for-visual-studio#57]
Currently using VS 2015. The interface to clone from a bitbucket repository does not include the option to clone git submodules of the repository. This requires a follow-on of the initial clone to manually init and update the submodules via the CLI or third-party application.

**Comment by MistyKuu** [comment]
Isn't it default?            https://github.com/MistyKuu/bitbucket-for-visual-studio/blob/e3fd2984a60c212ff36f949f9eb178e199e8e3fc/Source/GitClientVS.TeamFoundation.14/GitService.cs#L102

**Comment by BooherB** [comment]
I'll attempt to capture the failure in a log. It may be a git config setting on my end.
