### ISSUE TITLE
Latest version causes Visual Studio 15.7x to be unable to load any Xamarin project or even the Xamarin Tools

### ISSUE THREAD

**Issue by BOTLANNER** [MistyKuu/bitbucket-for-visual-studio#64]
The current stable version of this plugin caused my Visual Studio to be unable to load any Xamarin project or even the default Xamarin Tools in Visual Studio. I disabled all my extension and enabled each one one-by-one to pinpoint the issue, and this was the one that caused it.

**Comment by AmrAlSayed0** [comment]
This issue is discussed more here [Visual Studio Developer Community - Unable to load Android and iOS Projects (needs migration/incompatible)](https://developercommunity.visualstudio.com/content/problem/246920/unable-to-load-android-and-ios-projects-needs-migr.html).

**Comment by fzany** [comment]
I have the same Issue

**Comment by mduchev** [comment]
I have the same issue.

**Comment by polato94** [comment]
same problem here

**Comment by MistyKuu** [comment]
Is it also the case for older version of this plugin?

**Comment by fzany** [comment]
I do not know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FroggieFrog** [comment]
As stated above, a Microsoft employee has found a solution.
You need to update dependencies.
From: [https://developercommunity.visualstudio.com/content/problem/246920/unable-to-load-android-and-ios-projects-needs-migr.html](https://developercommunity.visualstudio.com/content/problem/246920/unable-to-load-android-and-ios-projects-needs-migr.html)

> Hi everyone, and thanks for taking the time to post each one of your experiences here.
> 
> We have determined this to be an issue with older versions of the Rx assemblies clashing with the one used in Xamarin bits. So far we have identified at least two extensions that use this: GitHub for VS and BitBucket. If you happen to have one of these installed and you disable it, this should fix the issue.
> 
> We are contacting these teams so they can update their Rx bits so this doesn't clash anymore. At the same time, we have updated our code to not use the type that was conflicting so going forward this shouldn't be an issue if these or other extensions happen to bundle Rx assemblies.
> 
> If anyone is still experiencing this after disabling the mentioned extensions please do ping me here (or via email VGA at microsoft dot com) so we can properly troubleshoot your install and see if there is another extension using Rx that may be causing this.
> 
> thanks,
> -VGA.

**Comment by MistyKuu** [comment]
I just tried to open IOS/Android Xamarin solutions and they work with this extension. Visual Studio 15.7.3. Has this been fixed?

**Comment by mduchev** [comment]
Yes, it is fixed. Please take a closer look at this comment:
https://developercommunity.visualstudio.com/solutions/255706/view.html

Basically, they have removed this dependency from their part (Rx assemblies), but they should have contacted you so that you remove it too from the extension.
