### ISSUE TITLE
Error creating pull request

### ISSUE THREAD

**Issue by MarcoTUI** [MistyKuu/bitbucket-for-visual-studio#66]
Hi,
we use the bitbucket extension to create pull requests. Unfortunatelly I always get this error creating a new one:
![image](https://user-images.githubusercontent.com/39701523/41773237-b084d402-761b-11e8-91c0-3aba33486b27.png)

The PullRequest itself is created, so everything seems to be ok with the pull request.

Let me know if you need any further informations.

Best regards
Marco

**Comment by skywqr** [comment]
Running into same issue while creating the pull request and merging the branch on VS2017.
Devs - is this project still under active development?

**Comment by MistyKuu** [comment]
Please refer to https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/63
