### ISSUE TITLE
Latest version 1.37.6 Error will using

### ISSUE THREAD

**Issue by AngelBermudez57** [MistyKuu/bitbucket-for-visual-studio#70]
Latest version 1.37.6 in VS2015 Started giving me this error. Not sure where to go from here. uninstall an reinstall does not fix it. Previous version still runs well running on VS2017 I do not dare to update it to latest version. Is there any way to go back to a previous version?

![bitbucketerror](https://user-images.githubusercontent.com/38950354/42037628-80e0d556-7aae-11e8-8060-f58ac1e0b920.jpg)

**Comment by MistyKuu** [comment]
I think the answer is pretty simple. I was forced to use background loading for the extension. It seems like there is a race condition issue. I'll take a look at it.

**Comment by MistyKuu** [comment]
Should be fixed in 1.37.7. Reopen if still the case.

**Comment by AngelBermudez57** [comment]
Thank you it is fixed now
