### ISSUE TITLE
Error when trying to start bitbucker session in visual studio 2017

### ISSUE THREAD

**Issue by oscarortiz18** [MistyKuu/bitbucket-for-visual-studio#72]
I have problems when trying to login in visual studio 2017. The error is: "Operation is forbidden"
Please support you to solve the problem.
Thanks in advance.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2160908/logs.txt)

**Comment by MistyKuu** [comment]
Hey, 
Please paste it in the browser and let me know what you get:
https://api.bitbucket.org/2.0/user

**Comment by oscarortiz18** [comment]
This is what comes out:

Because your Atlassian account admin requires single sign-on, you'll
need to authenticate with an app password. Create an app password at
https://bitbucket.org/account/admin/app-passwords

Regards,

*Atte. Oscar Ortiz Linares*

MCTS® | MCSA® | MCSE®

Operaciones y Servicios - CDI Project - cdiproject.pe

Comunal CoWorking: Av. Javier Prado 488 Piso 7 – Oficina CDI Project – San
Isidro Tlf. 702 6003

RPC: 992789523

2018-07-03 16:53 GMT-05:00 MistyKuu <notifications@github.com>:

**Comment by MistyKuu** [comment]
Hey,
please check this: https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/36
