### ISSUE TITLE
Error starting git-askpass.exe

### ISSUE THREAD

**Issue by AndyfromPBG** [MistyKuu/bitbucket-for-visual-studio#76]
Hi,

I'm getting the following two errors. I have the file specified as unreachable and have tried uninstalling and reinstalling both the extension and visual studio:

HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn /c/program files (x86)/microsoft visual studio/2017/enterprise/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Password for 'https://username@bitbucket.org': terminal prompts disabled

**Comment by luisllamasbinaburo** [comment]
Same here

**Comment by luisllamasbinaburo** [comment]
Solved with this procedure
1. Install the latest pre-release of Git Credential Manager for Windows.
2. cd "C:\Program Files\Git\mingw64\libexec\git-core", order files by "Date modified" descending, and copy top 6 files to "%DevEnvDir%\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core". You can view the value of %DevEnvDir% with "Developer Command Prompt for VS 2017" and the "set" command.
3. Confirm replacement.

Source: https://developercommunity.visualstudio.com/solutions/310409/view.html

**Comment by krunalc** [comment]
I was facing this issue since last 10 days or so and finally above trick fixed the issue for me. Thanks @luisllamasbinaburo

**Comment by MistyKuu** [comment]
@luisllamasbinaburo thanks mate,
