### ISSUE TITLE
Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp Version = 105.0.0.0

### ISSUE THREAD

**Issue by agrynco** [MistyKuu/bitbucket-for-visual-studio#8]
Visual Studio 2017
http://c2n.me/3KPnROl

**Comment by MistyKuu** [comment]
Seems like a deployment bug after fix made on Friday. I will look at this this evening and the fix should be deployed today.

**Comment by MistyKuu** [comment]
@agrynco any update on that?
