### ISSUE TITLE
error out when launching visual studio 2015

### ISSUE THREAD

**Issue by momsboy32** [MistyKuu/bitbucket-for-visual-studio#83]
When I start Visual studio the plugin fails to load. Here is end of my activity log.    

<entry>
    <record>122</record>
    <time>2018/08/23 17:56:18.095</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Global Search Package]</description>
    <guid>{18333854-D2FF-44A3-98D8-40501B914D7D}</guid>
  </entry>
  <entry>
    <record>123</record>
    <time>2018/08/23 17:56:18.095</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Global Search Package]</description>
    <guid>{18333854-D2FF-44A3-98D8-40501B914D7D}</guid>
  </entry>
  <entry>
    <record>124</record>
    <time>2018/08/23 17:56:18.128</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>125</record>
    <time>2018/08/23 17:56:18.128</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Unexpected system error mode before loading package [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>126</record>
    <time>2018/08/23 17:56:18.128</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>127</record>
    <time>2018/08/23 17:56:18.370</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>128</record>
    <time>2018/08/23 17:56:18.374</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [GitClientVSPackage]Source: &apos;GitClientVS.VisualStudio.UI&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.ComponentModelHost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.ComponentModelHost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.ComponentModelHost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at GitClientVS.VisualStudio.UI.GitClientVSPackage.&lt;InitializeAsync&gt;d__7.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at GitClientVS.VisualStudio.UI.GitClientVSPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{69C97FA4-92B5-448C-B5DB-037DD9C2C8B7}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>129</record>
    <time>2018/08/23 17:56:18.376</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [GitClientVSPackage]</description>
    <guid>{69C97FA4-92B5-448C-B5DB-037DD9C2C8B7}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by MistyKuu** [comment]
I have just pushed out 1.37.91 which basically uses old version of ComponenModelHost. Please let me know if it helped because I had to install them through Nuget Package which installed a lot of other dependencies

**Comment by momsboy32** [comment]
that worked perfectly thanks so much.
