### ISSUE TITLE
Unknown Error - No Repositories Show Up - Screenshot Shows Error

### ISSUE THREAD

**Issue by DanJ210** [MistyKuu/bitbucket-for-visual-studio#9]
Stoked to have a BitBucket extension finally. But I get some error and hitting a search button seems to crash VS2017 so I took a screenshot of what I see when I click clone. I'm assuming that clone should show my repos available.

![vs2017_bitbucket_extension](https://cloud.githubusercontent.com/assets/16159685/26756765/272e02c2-4878-11e7-8d4d-6b6286d34116.png)

**Comment by MistyKuu** [comment]
Hey Dan,
Please attach the log located under %AppData%\GitClientVsExtension\logs.txt. I'll investigate it further later today.

**Comment by DanJ210** [comment]
I was going to attach the file.

[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/1050505/logs.txt)

**Comment by DanJ210** [comment]
@MistyKuu Should I make a new post?

**Comment by MistyKuu** [comment]
No,  I have fixed it already.  You can the commit in the previous post.  I just haven't released it yet.

**Comment by DanJ210** [comment]
Oh ok well thanks. I'm with a company, Onsolve, and I have some of the engineers waiting on me to let them know when this is working. So you've got people using it when it's ready!

**Comment by MistyKuu** [comment]
@DanJ210 Cool! I've just released under 1.35.3 for you guys. It should be visible shortly in the marketplace. Please let me know if it fixed the issue.
By the way remember that you can always clone it using git and then choose is as active repository in Team Explorer to take advantage of other features.

**Comment by DanJ210** [comment]
@MistyKuu Thanks. I'll keep an eye out and let you know.

Yea we all do use regular git cloning but thought it was neat to have an actual BitBucket extension. I'm pretty fluent with Team Explorer for the most part. But we like the having the extension!

So thanks for the work.
