### ISSUE TITLE
Cannot merge pull requests until all conflicts get resolved

### ISSUE THREAD

**Issue by saifobeidat** [MistyKuu/bitbucket-for-visual-studio#92]
Hi guys , 

I viewed the pull requests using this extension, I tried to merge a pull request but i got  this message  : 

> You can't merge until you resolve all merge conflicts

![Image of Yaktocat](https://i.ibb.co/2qFX53R/Resolve.jpg)

How can i resolve conflicts ?? , there's no button or any indicator to resolve conflicts ..

Many thanks

**Comment by MistyKuu** [comment]
![image](https://user-images.githubusercontent.com/10333668/52435803-02089280-2b13-11e9-93ba-9366cd6855db.png)
Use "Changes" in Team Explorer. This functionality is in visual studio.
