### ISSUE TITLE
Can't build Test projects from source

### ISSUE THREAD

**Issue by PjotrB** [MistyKuu/bitbucket-for-visual-studio#94]
Two of the Test projects (Bitbucket.REST.API.Tests + GitClientVS.Infrastructure.Tests) depend on very old `Microsoft.Reactive` / `System.Reactive` versions. In fact so old that these dependencies aren't even present in `packages.config`, they only exist in the `.csproj` files (so the referenced .dlls have to exist magically).

The referenced version is 2.3.0.0:

    <Reference Include="Microsoft.Reactive.Testing, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-Testing.2.3.0-beta2\lib\net46\Microsoft.Reactive.Testing.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.Core, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-Core.2.3.0-beta2\lib\net46\System.Reactive.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.Interfaces, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-Interfaces.2.3.0-beta2\lib\net46\System.Reactive.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.Linq, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-Linq.2.3.0-beta2\lib\net46\System.Reactive.Linq.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.PlatformServices, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-PlatformServices.2.3.0-beta2\lib\net46\System.Reactive.PlatformServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.Windows.Threading, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\..\packages\Rx-XAML.2.3.0-beta2\lib\net46\System.Reactive.Windows.Threading.dll</HintPath>
    </Reference>

The HintPath is nowhere to be found after doing `git clone` + `package restore`. Also the oldest version on NuGet of these packages is v3.0.0, so Install+Restore is only possible to a higher version (for which I can't oversee the consequences).

Quickest 'fix' was either to delete these Test projects from the Solution, or to disable them both in the `Debug` + `Release` Build configs, and then I could successfully build.

**Comment by MistyKuu** [comment]
It seems like there was a cleanup on nuget. Some old packages have disappeared. I'll updae that when I get a chance.
